require "lsp/nvim-lspconfig"
require "lsp/mason"
require "lsp/lsp_signature"

require "lsp/pyright"
require "lsp/clangd"
require "lsp/lua_ls"
require "lsp/gopls"
require "lsp/rust-analyzer"
require "lsp/html-lsp"
require "lsp/texlab"
